# Generated by Django 4.2.7 on 2023-11-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('timeStart', models.CharField(max_length=50)),
                ('timeEnd', models.CharField(blank=True, max_length=50)),
                ('allDay', models.BooleanField()),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
