# Generated by Django 4.2.7 on 2023-11-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.ImageField(default=None, upload_to='icons/'),
            preserve_default=False,
        ),
    ]
